# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'EduCare' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
  # Pods for EduCare

  target 'EduCareTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'EduCare-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EduCare-tvOS

  target 'EduCare-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
post_install do |installer|
  system("mkdir -p Pods/Headers/Public/FirebaseCore && cp Pods/FirebaseCore/Firebase/Core/Public/* Pods/Headers/Public/FirebaseCore/")
end